/* API_BASE_URL can be set before this file loads, e.g. window.VoxaConfig={API_BASE_URL:'https://api.example.com'} */
const API_BASE_URL = (window.VoxaConfig?.API_BASE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '');
const $ = (id) => document.getElementById(id);
const question = $('question'), transcript = $('transcript'), recordButton = $('record'), submitButton = $('submit');
let recorder, stream, recognition, chunks = [], recording = false, activeUtterance = null, history = JSON.parse(localStorage.getItem('voxa-history') || '[]');
const wave = $('waveform');

function setupBars() { document.querySelectorAll('.bars').forEach(container => { if (!container.children.length) for(let i=0;i<22;i++){ const b=document.createElement('span'); b.style.height=`${8+(i%7)*4}px`; b.style.animationDelay=`${i*.055}s`; container.append(b); } }); }
function languageName() { return $('language').selectedOptions[0].text; }
function setRecording(next) { recording=next; recordButton.classList.toggle('is-recording',next); document.querySelector('.ask-card').classList.toggle('recording',next); $('record-icon').textContent=next?'■':'🎙'; $('recording-status').textContent=next?`Recording in ${languageName()} — tap to stop.`:''; }
function displayError(message) { $('answer-empty').classList.remove('hidden'); $('answer-empty').innerHTML=`<div class="sparkle">!</div><p>${message}</p>`; $('answer-content').classList.add('hidden'); $('answer-state').textContent='Unable to answer'; }
function resetAnswerEmpty() { $('answer-empty').innerHTML='<div class="sparkle">✦</div><p>Your answer will appear here.<br />Ask with your voice or keyboard.</p>'; }
function setLoading(message='Finding a grounded answer…') { $('answer-empty').classList.remove('hidden'); $('answer-empty').innerHTML=`<div class="sparkle">✦</div><p>${message}</p>`; $('answer-content').classList.add('hidden'); $('sources').classList.add('hidden'); $('answer-state').textContent='Thinking…'; submitButton.disabled=true; submitButton.textContent='Asking…'; }
function finishLoading(){submitButton.disabled=false;submitButton.innerHTML='Ask VOXA <span>→</span>';}
async function askText(text) { setLoading(); try { const response = await fetch(`${API_BASE_URL}/api/query`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:text,top_k:5,rerank:false})}); const data=await readResponse(response); showAnswer({...data,query:text}); } catch (error) { displayError(error.message || `Couldn’t reach VOXA’s backend at ${API_BASE_URL}.`); } finally { finishLoading(); } }
async function askVoice(blob) { setLoading('Transcribing your voice…'); try { const form=new FormData(); form.append('audio',blob,'voxa-recording.webm'); const response=await fetch(`${API_BASE_URL}/api/transcribe`, {method:'POST',body:form}); const data=await readResponse(response); const text=data.text||data.transcript||data.query||''; if(!text)throw new Error('The transcription service returned no spoken text.'); question.value=text; transcript.textContent=`Transcribed: ${text}`; await askText(text); } catch(error) { displayError(error.message || `Voice request failed. Check microphone access and that VOXA’s backend is running at ${API_BASE_URL}.`); } finally { finishLoading(); } }
async function readResponse(response){let data;try{data=await response.json()}catch{throw new Error('Invalid server response')}if(!response.ok){const detail=data.detail;throw new Error(typeof detail==='string'?detail:(detail?.message||detail?.code||'Request failed'));}return data;}
function showAnswer(data) { stopSpeaking(); const answer=data.answer||data.response||data.result?.answer||'The backend returned no answer.'; $('answer-empty').classList.add('hidden'); $('answer-content').classList.remove('hidden'); $('answer-text').textContent=answer; $('answer-state').textContent=data.blocked_reason?'Safety response':'Grounded answer'; const meta=[]; if(data.blocked_reason)meta.push(`Status: ${data.blocked_reason}`); if(data.confidence !== undefined)meta.push(`Confidence: ${Math.round(data.confidence*100)}%`); if(data.timings?.total_ms !== undefined)meta.push(`${Math.round(data.timings.total_ms)} ms`); if(data.latency_ms !== undefined)meta.push(`${Math.round(data.latency_ms)} ms`); $('answer-meta').innerHTML=meta.map(x=>`<span>${x}</span>`).join(''); const sources=data.retrieved_chunks||data.sources||data.context||data.retrieved_context||data.result?.sources; if(Array.isArray(sources)&&sources.length){$('sources').classList.remove('hidden');$('sources-list').innerHTML=sources.map((item,i)=>`<div class="source-item"><b>${i+1}.</b> ${typeof item==='string'?item:(item.text||item.content||JSON.stringify(item))}</div>`).join('');}else $('sources').classList.add('hidden'); $('speak-answer').disabled=false;$('copy-answer').disabled=false;$('clear-answer').disabled=false;$('ask-another').classList.remove('hidden'); saveHistory(data.query||question.value,answer); }
function saveHistory(query,answer){if(!query)return;history=[{query,answer,time:Date.now()},...history.filter(x=>x.query!==query)].slice(0,6);localStorage.setItem('voxa-history',JSON.stringify(history));renderHistory();}
function renderHistory(){$('history-count').textContent=`${history.length} saved`;$('history-list').innerHTML=history.length?history.map((item,i)=>`<button class="history-item" data-history="${i}" title="${item.query}">${item.query}</button>`).join(''):'<p class="history-empty">Your question history stays in this browser.</p>';document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{question.value=history[b.dataset.history].query;question.focus();});}
function updateListenButton(isSpeaking){const button=$('speak-answer');button.innerHTML=isSpeaking?'■ <span>Stop</span>':'▷ <span>Listen</span>';button.setAttribute('aria-pressed',String(isSpeaking));}
function speechLanguage(){return $('language').value||'en-IN';}
function selectVoice(language){const voices=window.speechSynthesis.getVoices();if(!voices.length)return null;const root=language.split('-')[0].toLowerCase();return voices.find(voice=>voice.lang.toLowerCase()===language.toLowerCase())||voices.find(voice=>voice.lang.toLowerCase().startsWith(`${root}-`))||voices.find(voice=>voice.default)||voices[0];}
function stopSpeaking(){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();activeUtterance=null;updateListenButton(false);}
function speakCurrentAnswer(){const text=$('answer-text').textContent.trim();if(!text||!('speechSynthesis'in window))return;if(window.speechSynthesis.speaking||window.speechSynthesis.pending){stopSpeaking();return;}const utterance=new SpeechSynthesisUtterance(text);const language=speechLanguage();utterance.lang=language;const voice=selectVoice(language);if(voice)utterance.voice=voice;utterance.onstart=()=>{activeUtterance=utterance;updateListenButton(true);};utterance.onend=()=>{if(activeUtterance===utterance){activeUtterance=null;updateListenButton(false);}};utterance.onerror=()=>{if(activeUtterance===utterance){activeUtterance=null;updateListenButton(false);}};activeUtterance=utterance;updateListenButton(true);window.speechSynthesis.speak(utterance);}
function browserTranscription(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return null;const r=new Recognition();r.lang=$('language').value;r.continuous=true;r.interimResults=true;r.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript;else interim+=e.results[i][0].transcript;}if(final)question.value=`${question.value} ${final}`.trim();transcript.textContent=interim?`Listening: ${interim}`:`Transcribed: ${question.value}`;};r.onerror=e=>{$('recording-status').textContent=`Speech recognition: ${e.error}. Audio will still be sent to the backend.`;};return r;}
async function toggleRecord(){if(recording){recorder?.stop();recognition?.stop();return;}if(!navigator.mediaDevices?.getUserMedia){$('recording-status').textContent='Recording is not supported in this browser.';return;}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{stream?.getTracks().forEach(t=>t.stop());setRecording(false);const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});if(blob.size)askVoice(blob);};recognition=browserTranscription();recognition?.start();recorder.start();setRecording(true);transcript.textContent='Listening…';}catch(error){$('recording-status').textContent='Microphone access was blocked. You can still type your question.';}}
recordButton.onclick=toggleRecord;submitButton.onclick=()=>{const text=question.value.trim();if(!text){question.focus();$('recording-status').textContent='Type a question or use the microphone first.';return;}askText(text);};$('clear-question').onclick=()=>{question.value='';transcript.textContent='Your live transcription will appear here.';};$('copy-answer').onclick=async()=>{try{await navigator.clipboard.writeText($('answer-text').textContent);$('copy-answer').textContent='✓ Copied';setTimeout(()=>$('copy-answer').innerHTML='⧉ Copy',1400)}catch{}};$('clear-answer').onclick=clearAnswer;$('ask-another').onclick=()=>{question.value='';clearAnswer();question.focus();};$('speak-answer').addEventListener('click',speakCurrentAnswer);
['keydown'].forEach(event=>question.addEventListener(event,e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();submitButton.click();}}));
document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12}).observe(el));
const languages=['English','Hindi','Kannada'];let langIndex=0;setInterval(()=>{$('rotating-language').textContent=languages[++langIndex%languages.length]},2100);setupBars();renderHistory();
